### ISSUE TITLE
Krasch ungefär 60s efter AinAppen startar på emulatorn

### ISSUE THREAD

**Issue by Rovanion** [Rovanion/AinAppen#36]
Den bristande punkten verkar vara

```
05-05 13:49:21.026: E/SQLiteLog(1963): (1) table cases has no column named author
```

Men. Det kan också vara att för att det inte finns någon anslutning för telefonen, det är nämligen så att min case-lista är tom, så misslyckas hämntningen efter någon viss timeout och då försöks det att sättas in en tom rad eller någonting med väldigt mycket null i på den raden.

```
05-05 13:48:20.825: D/dalvikvm(1963): GC_FOR_ALLOC freed 132K, 7% free 3483K/3728K, paused 2ms, total 2ms
05-05 13:48:20.825: I/dalvikvm-heap(1963): Grow heap (frag case) to 4.582MB for 1127532-byte allocation
05-05 13:48:20.845: D/dalvikvm(1963): GC_FOR_ALLOC freed 1K, 6% free 4582K/4832K, paused 15ms, total 15ms
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.Case
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.Contact
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.LocalID
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.User
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.MapPoint
05-05 13:48:20.875: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.LocalMapPointID
05-05 13:48:20.905: W/EGL_emulation(1963): eglSurfaceAttrib not implemented
05-05 13:49:20.956: D/dalvikvm(1963): GC_FOR_ALLOC freed 273K, 8% free 4898K/5280K, paused 2ms, total 3ms
05-05 13:49:21.016: I/OpenHelperManager(1963): helper was already closed and is being re-opened
05-05 13:49:21.016: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.Case
05-05 13:49:21.026: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.Contact
05-05 13:49:21.026: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.LocalID
05-05 13:49:21.026: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.User
05-05 13:49:21.026: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.MapPoint
05-05 13:49:21.026: I/DaoManager(1963): Loaded configuration for class gov.polisen.ainappen.LocalMapPointID
05-05 13:49:21.026: E/SQLiteLog(1963): (1) table cases has no column named author
05-05 13:49:21.026: D/AndroidRuntime(1963): Shutting down VM
05-05 13:49:21.026: W/dalvikvm(1963): threadid=1: thread exiting with uncaught exception (group=0xb0cbeb20)
05-05 13:49:21.026: E/AndroidRuntime(1963): FATAL EXCEPTION: main
05-05 13:49:21.026: E/AndroidRuntime(1963): Process: gov.polisen.ainappen, PID: 1963
05-05 13:49:21.026: E/AndroidRuntime(1963): java.lang.RuntimeException: java.sql.SQLException: Unable to run insert stmt on object gov.polisen.ainappen.Case@b0ffad08: INSERT INTO `cases` (`deviceID` ,`caseID` ,`author` ,`modificationTime` ,`firstRevisionCaseID` ,`firstRevisionDeviceID` ,`deletionTime` ,`classification` ,`status` ,`priority` ,`longitude` ,`latitude` ,`timeOfCrime` ,`description` ,`localCaseID` ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.dao.RuntimeExceptionDao.create(RuntimeExceptionDao.java:228)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at gov.polisen.ainappen.LocalDBHandler.addExistingCase(LocalDBHandler.java:107)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at gov.polisen.ainappen.ExternalDBHandeler$SyncDB.syncWithLocalDB(ExternalDBHandeler.java:143)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at gov.polisen.ainappen.ExternalDBHandeler$SyncDB.onPostExecute(ExternalDBHandeler.java:97)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at gov.polisen.ainappen.ExternalDBHandeler$SyncDB.onPostExecute(ExternalDBHandeler.java:1)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.os.AsyncTask.finish(AsyncTask.java:632)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.os.Looper.loop(Looper.java:136)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.app.ActivityThread.main(ActivityThread.java:5017)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at java.lang.reflect.Method.invokeNative(Native Method)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at java.lang.reflect.Method.invoke(Method.java:515)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at dalvik.system.NativeStart.main(Native Method)
05-05 13:49:21.026: E/AndroidRuntime(1963): Caused by: java.sql.SQLException: Unable to run insert stmt on object gov.polisen.ainappen.Case@b0ffad08: INSERT INTO `cases` (`deviceID` ,`caseID` ,`author` ,`modificationTime` ,`firstRevisionCaseID` ,`firstRevisionDeviceID` ,`deletionTime` ,`classification` ,`status` ,`priority` ,`longitude` ,`latitude` ,`timeOfCrime` ,`description` ,`localCaseID` ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.dao.RuntimeExceptionDao.create(RuntimeExceptionDao.java:225)
05-05 13:49:21.026: E/AndroidRuntime(1963):     ... 15 more
05-05 13:49:21.026: E/AndroidRuntime(1963): Caused by: java.sql.SQLException: inserting to database failed: INSERT INTO `cases` (`deviceID` ,`caseID` ,`author` ,`modificationTime` ,`firstRevisionCaseID` ,`firstRevisionDeviceID` ,`deletionTime` ,`classification` ,`status` ,`priority` ,`longitude` ,`latitude` ,`timeOfCrime` ,`description` ,`localCaseID` ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:169)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
05-05 13:49:21.026: E/AndroidRuntime(1963):     ... 18 more
05-05 13:49:21.026: E/AndroidRuntime(1963): Caused by: android.database.sqlite.SQLiteException: table cases has no column named author (code 1): , while compiling: INSERT INTO `cases` (`deviceID` ,`caseID` ,`author` ,`modificationTime` ,`firstRevisionCaseID` ,`firstRevisionDeviceID` ,`deletionTime` ,`classification` ,`status` ,`priority` ,`longitude` ,`latitude` ,`timeOfCrime` ,`description` ,`localCaseID` ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:992)
05-05 13:49:21.026: E/AndroidRuntime(1963):     at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:155)
05-05 13:49:21.026: E/AndroidRuntime(1963):     ... 19 more
```

**Comment by Rovanion** [comment]
Kanske lite trist om appen kraschar mitt under presentation.

**Comment by Rovanion** [comment]
Stänger den här issue:n eftersom att buggen inte verkar uppstå längre.
